# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a15ce8b9d783e4d1f8366fd7484e35f9688123b1f24f2796699154a785a9a65815354385b42d8ffd8ac14363c7390356c4d4ab7ee11dcbd297db05977e49e948

test:
  secret_key_base: 658da71b06e6ab846ae5c79c265c26f6c8a665e92d38afc23a152dff29fb07bb94c6aa43e68c11491d805732c806705a25464ad7ca711c2d2f70928a20a3dc9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
